### ISSUE TITLE
Cloned solution examples do not work as is

### ISSUE THREAD

**Issue by mika76** [JBildstein/SpiderEye#9]
* If I try to run the App.Windows simple example, the icon.ico file is missing (I copied it from another folder to make it run)

* Running the spa example (also windows) the icons folder and the icon.ico file are also missing so the app crashes. Once placed in there though, the app runs, but the window is just blank.

* Running the spa example, in debug mode, I get the warning (in VS2019) that the app is running in Release mode and would I like to continue debugging (weird because I checked and everything is compiled in debug)

This is all from just cloning the project as is and running in VS2019...

**Comment by ABildstein** [comment]
Thank you for the report!

 The icon issues are fixed now, those were leftovers from the old examples.

As for the blank window, you are probably running Windows 10, correct? In that case you'll have to call this in a console
```
checknetisolation LoopbackExempt -a -n=Microsoft.Win32WebViewHost_cw5n1h2txyewy
```
to enable calling a localhost address in the Edge webview. (the Angular dev server is running on localhost).
See the readme for more details on that: [Windows 10 Edge and localhost](https://github.com/JBildstein/SpiderEye#windows-10-edge-and-localhost)
Alternatively (sort of), you can force using the IE webview by setting `config.ForceWindowsLegacyWebview = true`

The debug warning I'm not a 100% sure what that's about, but it's probably due to missing symbols in the SpiderEye NuGet package. I'll have to look into that some more. For now, just click "Continue Debugging" and it should work as usual.

**Comment by ABildstein** [comment]
I have looked into the debug warning some more now and I believe that this is a Visual Studio bug.

If I create a new project outside of this one, everything works fine. Same if I copy the Examples\Simple folder outside of the current sln (bin and obj folder and all) and run that.

**Comment by mika76** [comment]
Thanks, I've updated and tried again. So the checknetisolation file was not in my path which was a bit confusing, but I found it in Windows\System32 so I ran that, but I still have issues running the projects from command line, maybe I'm running them wrong.

If I run (in admin powershell) `dotnet run --project App.Windows` from the Examples/simple folder, the prog seems to run but no window opens. I waited for quite a while...

Trying to run the spa sample like that also didn't open a window.

So the only thing that works for me is to run it in VS2019 - I change the startup project to examples/spa/app.windows projects and run that. I still get the debug error but I click continue. A window opens, but it's still blank.

I then realised the angular app was not built, so I went and run `npm install` and `npm run build:prod` and got the dist folder, but still when I run the spa project I get a blank window.

Then I noticed the publish.bat file, so I ran that - it build and created the published folder, and running the spa example exe file the window opens and the SPA example works.

So I think maybe just some guidance would be needed to get the apps and examples up and running when cloning the project would be helpful (not just creating a new template)

Anyway - nice project - wish you luck :)

**Comment by ABildstein** [comment]
Thank you for the feedback, I'll improve on the documentation and try to add some immediate feedback if something is missing or isn't working as it should.

Running the examples as admin (powershell or cmd) indeed doesn't seem to work. I'm not sure what the problem is yet. If you run it with normal (non-admin) rights it works as it should.

As for the SPA example, that's my fault for not documenting this. To run it in Debug mode you have to have the angular dev server running. You can do that by opening a console window in the App.Core folder and then running `npm run watch`. The SPA example is set up in a way that uses the angular dev server as source for the files in Debug and uses the Angular\dist folder (created by running `npm run build:prod`) as source in Release mode.

Thank you again, it was very helpful!
